// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cprmgpzpcbxlwesbbcgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcm1ncHpwY2J4bHdlc2JiY2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzEwMjcsImV4cCI6MjA2MjA0NzAyN30.aiAcfDxZcyoSEgz3xfVnINs0eQW6Hev7xkNcwwdEp6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);